M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2026-01-12T20:01:16+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T20:01:16+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X131.0Y-62.0
X145.0Y-86.0
X159.5Y-61.5
M30
